# Generated by Django 5.1.7 on 2026-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_submissionlog',
            name='EnrollmentNo',
            field=models.CharField(db_column='EnrollmentNo', max_length=50),
        ),
        migrations.AlterModelOptions(
            name='academic_allocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='academic_subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculty_teacher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_response',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_submissionlog',
            options={},
        ),
        migrations.DeleteModel(
            name='Users_Student',
        ),
    ]
