# Generated by Django 5.1.7 on 2026-02-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_alter_feedback_submissionlog_enrollmentno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_submissionlog',
            options={'managed': False},
        ),
    ]
